### ISSUE TITLE
Add optional GPU monitoring support

### ISSUE THREAD

**Issue by amete** [HSF/prmon#105]
Hi,

I'm creating this issue to follow-up on the discussion that was held at the ATLAS SPOT meeting where we discussed adding GPU monitoring support to `prmon`.

Currently the easiest and the most reliable/useful information seems to be provided by the utilities that are developed by the hardware manufacturers, e.g. `nvidia-smi`.  

For the initial implementation, the agreed-upon idea is to write a new plug-in, where we invoke `nvidia-smi` to gather GPU statistics and add these to the rest. The rationale behind this choice is the wide usage of NVIDIA accelerators where `prmon` is used, the minimum dependency at the compilation/installation time (as opposed to using the C API) etc. The implementation will be done with the understanding that support for other hardware, eg. Intel/AMD, can/will be added in the future.

Looking at the relevant documentation, e.g. [here](https://developer.download.nvidia.com/compute/DCGM/docs/nvidia-smi-367.38.pdf), it seems as if `nvidia-smi` supports different options, the most relevant ones being `dmon` which provides device monitoring and `pmon` which provides process monitoring statistics. There are a number of concerns in terms of the overhead of using the command-line utility etc. but these will need to be assessed as the project progresses.

Please feel free to provide relevant input under this ticket. Many thanks.

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
I started to work on this a bit and to think about how to do it.

Adding new monitor code is pretty easy (let's say `nvidiamon.{cpp,h}`), but we can't really guarantee that this is going to be useful or useable. We should have another attribute that determines if NVIDIA GPU monitoring seems to be available. That should invoke `nvidia-smi -L` and see if (a) it works at all and if (b) it detects a GPU on the system.

Running the monitoring loop means invoking `nvidia-smi` and reading the output from a pipe. The easy way is using `popen()` although this does cost a shell invocation, so it's not the most efficient way (see <https://www.gnu.org/software/libc/manual/html_node/Pipe-to-a-Subprocess.html>).

Assuming that monitoring is useful, we need to work out what to monitor. Just a note that some complications may arise:

- Systems with multiple GPUs, but we are only interested in one/some that have been assigned to this job slot
- GPUs which are shared between users, so that not all of the GPU usage is attributable to the processes we are interested in

Doug mentioned some Slurm functionality for assigning GPUs, so we should follow up and see if we can harvest useful information from that (I assume the system is not so smart that it can actually mask out other GPUs).

`nvidia-smi` can print the unix PIDs of processes that are using the GPU, so that could be filtered (and the question is, could the GPUs change during the job?).

A few other issues:

- What to report? GPU utililisation (%) (or fraction, 0.0-1.0) and memory would be the useful baseline, IMO
- When multiple GPUs are being used, what do we report? Each one or an average? (could print the number of GPUs active in each iteration, then the average of the interesting ones)
  - N.B. The output format has to be CSV, so fixed number of columns
- Do we report at all on the GPU types or leave this to some other part of the overall system? (At the moment the ATLAS pilot takes care of reporting on CPU types.)

**Comment by amete** [comment]
Hi @graeme-a-stewart,

I also played around w/ `nvidia-smi pmon` a bit, which is advertised to give process-level statistics:

```
$ nvidia-smi pmon --help

    Process statistics are displayed in scrolling format per sampling
    interval. This tool lists the statistics for all the compute and 
    graphics processes running on each device. Metrics to be monitored
     can be adjusted based on the width of terminal window. Monitoring
    is limited to a maximum of 4 devices. If no devices are specified,
    then up to first four supported devices under natural enumeration
    (starting with GPU index 0) are used for monitoring purpose.
    It is supported on Tesla, GRID, Quadro and limited GeForce products
    for Kepler or newer GPUs under x64 and ppc64 bare metal Linux.

    Usage: nvidia-smi pmon [options]

    Options include:
    [-i | --id]:          Comma separated Enumeration index, PCI bus ID or UUID
    [-d | --delay]:       Collection delay/interval in seconds [default=1sec, max=10secs]
    [-c | --count]:       Collect specified number of samples and exit
    [-s | --select]:      One or more metrics [default=u]
                          Can be any of the following:
                              u - Utilization
                              m - FB memory usage
    [-o | --options]:     One or more from the following:
                              D - Include Date (YYYYMMDD) in scrolling output
                              T - Include Time (HH:MM:SS) in scrolling output
    [-f | --filename]:    Log to a specified file, rather than to stdout
    [-h | --help]:        Display help information
```

For example:

```
# gpu        pid  type    sm   mem   enc   dec   command
# Idx          #   C/G     %     %     %     %   name
    0      14835     C    45    15     0     0   python         
    1      14945     C    64    50     0     0   python
(in this case, two different python processes are running; one on each GPU)
```

From what I can decipher, `sm` is the percentage time (over the past sample period) during which one or more kernels from the given process was executing on the GPU, `mem` is the same for (device) memory, and `enc` and `dec` area the same for video encoding/decoding (which only is meaningful if the type is graphics - I believe). Presumably we'd be primarily interested in `sm` and `mem` but that's a guesstimate.

This mode can continuously monitor the usage w/ a pre-defined interval and dump the results into a file. I was thinking if we can fork a new process, run the sampling there continuously along side `prmon`, dump the results into a file and read the measurement from there. This way we don't have to do a shell invocation for every sampling.

Having said that, the documentation says this mode works for at most four devices at a time. So, potentially we'd be missing out on possible devices/processes. 

On the otherhand, `dmon` seems to provide overall GPU usage which accounts for all processes running on the device as far as I understand. But, this'll be device-level monitoring as we do for networking.

**Comment by graeme-a-stewart** [comment]
Hi @amete 

Yes, I think that `pmon` is the way to go. As the architecture is that we get a list of PIDs that are relevant for prmon then we can filter the `pmon` output to pickup only the GPU usage that is relevant for us. The 4 device limit could be an issue - at least at startup we can see if there are more than 4 devices.

The problems with running the monitoring in the background are:

- We have to be really careful not to leave the process behind after we exit
- What if the process dies for some reason?
- Parsing the text file is not 100% trivial - header lines appear and there are no timestamps
- The file seems to be buffered, writing blocks at a time (so nothing for ages, then a splurge of values)
- Related: obvious race conditions when reading from a file that a process is actively writing to

So I would prefer to simplify things and invoke per monitoring cycle, at least for a first implementation. It seems to be quite cheap to run (13ms).

Adding the `-s um` option seems to get us memory information in MB, which would be more useful (and consistent with the host metrics).

```
graemes@titanx ~ $ time nvidia-smi pmon -s um -c 1
# gpu        pid  type    sm   mem   enc   dec    fb   command
# Idx          #   C/G     %     %     %     %    MB   name
    0       1118     C    96    32     0     0 11351   python         
    1       1118     C    79    32     0     0 11351   python         

real	0m0.034s
user	0m0.002s
sys	0m0.013s
```

**Comment by graeme-a-stewart** [comment]
Just as a status update, my WIP branch is <https://github.com/HSF/prmon/tree/nvidia-mon>.

I developed the infrastructure to execute external processes (which is always more tricky than one thinks). The nvidiamon code uses this to check at startup if there seems to be a suitable GPU setup to enable monitoring.

One question would be would users like GPU monitoring always to be attempted, or if this should be an optional piece. (There was thought to make all of the monitoring modules switchable, but we didn't ever implement that.)

**Comment by amete** [comment]
Thanks a lot @graeme-a-stewart. I'll give this a try as I have a machine w/ a GPU now.

On the last point, I guess both have pros and cons. My initial inclination would be making it optional, primarily because it depends on an external tool whose existence depends on a specific hardware that is not super widespread yet. However, I'm not strongly opinionated on that front.

**Comment by graeme-a-stewart** [comment]
Hi @amete. It's quite cheap to test this and the monitoring is disabled if it's not possible. The undesirable case would be if there are GPUs, but not used by out job, so then the monitoring is done (which costs), but to no good end. We should ask.

At the moment nothing really works yet, but I will let you know when it's at least alpha quality ;-)

**Comment by amete** [comment]
Hi @graeme-a-stewart,

Sure, customer is always right :) I guess there is no good way to know when a process would utilize the GPU or not, so as long as we enable it, it'll have to be there.

Let me know how I can be of any help. I also have a bit of time to look into this these days.

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
Hi @amete - the current head of the [nvidia-mon](https://github.com/HSF/prmon/tree/nvidia-mon) branch pretty much works for me, at least for running my one GPU loading process. It's still a WIP and prints a pile of debug info (it would be nice to have a *real* verbose/debug mode).

Reported stats are:

- Number of GPUs used, x100 (`n100gpu`)
- %age gpu-cycles (the "sm" attribute; `gpusm`)
- gpu memory use in MB ("fb" attribute; `gpufbmem`)

All of the internals of prmon are currently integer types, so the n_gpu figure has a problem as it always rounds down. So as a workaround I report n_gpus * 100, so that the division gives a sensible answer (i.e. `"n100gpus": 92` means average use of 0.92 GPUs). However, we should think how to make some values report as floats...

It's a good time to solicit feedback from people on what we are intending to report - another SPOT meeting soon?

**Comment by amete** [comment]
Hi @graeme-a-stewart,

Looks like a great start! I just ran over a dummy burner code I put together and I also seem to be getting meaningful results, e.g.:

```
nvidiamon::update_stats got the following output (5): 
0 -> # gpu        pid  type    sm   mem   enc   dec    fb   command
1 -> # Idx          #   C/G     %     %     %     %    MB   name
2 ->     0       2381     G     0     0     0     0    39   Xorg           
3 ->     0       2410     G     0     0     0     0    71   gnome-shell    
4 ->     0      24311     C   100     0     0     0    83   burner         
Good read: 0 2381 G 0 0 0 0 39 Xorg
Good read: 0 2410 G 0 0 0 0 71 gnome-shell
Good read: 0 24311 C 100 0 0 0 83 burner
Parsed: 100 100 83
```

A few quick (albeit not super crucial) feedback: 

- `fb` seems to report the memory usage in `MB` unlike all other memory metrics we have. I think it would be nice to unify w/ the rest. 
- For `ngpus`, I think we currently have the same _feature_ for `nthreads` and `nprocs` :) Whatever we choose to do, we should unify. That's essentially a problem for the `json` w/ the averages and not necessarily the `txt` file where we report the actual count at the time of each sampling, is that correct?

In any case, yes, I think we can have a quick discussion on this to get feedback. I'll start a thread.

**Comment by graeme-a-stewart** [comment]
Status update:

- The issues with rounding of average values have been fixed with #110, so the `ngpus` monitoring is now more meaningful (and the workaround of x100 as `n100gpus` is dropped)
- Memory values are converted to kB to match other values reported by prmon
- Verbose output from the `nvidiamon` component is suppressed, but can be re-enabled by defining `NVIDIA_DEBUG` to `1` and recompiling (will be fixed properly with the solution to #106)

So at this point we wait for some feedback on the development in this branch

**Comment by graeme-a-stewart** [comment]
Started to look at the hardware report we could provide for GPUs. The easiest way to get this is from the `nvidia-smi --query-gpu=` option. Briefly, I think the interesting things would be GPU model name, total memory and SM clock frequency:

```
titanx:~/prmon$ nvidia-smi --query-gpu=gpu_name,memory.total,clocks.max.sm --format=csv,noheader        
TITAN Xp, 12196 MiB, 1911 MHz
TITAN Xp, 12195 MiB, 1911 MHz
```

I would expect that almost all nodes would have identical GPUs, but that's not actually guaranteed, so is it safer to return GPU by GPU stats?

**Comment by amete** [comment]
Looking at the manual there are tons of different options but I think this is a good start. I noticed that it also accepts `count` as an option, for example in the single GPU machine that I have I get:

```
$ nvidia-smi --query-gpu=count,gpu_name,memory.total,clocks.max.sm --format=csv,noheader
1, GeForce RTX 2060, 5933 MiB, 2100 MHz
```

So I wonder, if in a machine w/ multiple GPUs (possibly different models) this prints each unique type w/ the total count or not. If so, this might make parsing the output a little easier perhaps. We can store one entry per type, instead of one per unit.

On a similar footing, for the CPU we currently assume each physical socket has the same hardware, which doesn't necessarily have to be true (although in practice I'm not sure how much people mix because it's not super straightforward). We can update the logic there, too, to align the approach.

**Comment by graeme-a-stewart** [comment]
I think the CPU assumption is safe - I never saw a motherboard where sockets had different CPUs.

For the GPUs, I suspect that production machines will be homogeneous, but test machines might have different models? Anyway, it's a proposal. Last commit gives:

```
  "HW": {
    "cpu": {
      "model name": "Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz",
      "nCPU": 16,
      "nCoresPerSocket": 8,
      "nSockets": 1,
      "nThreadsPerCore": 2
    },
    "gpu": {
      "gpu_0": {
        "name": "TITAN",
        "sm_freq": 1911,
        "total_mem": 12488704
      },
      "gpu_1": {
        "name": "TITAN",
        "sm_freq": 1911,
        "total_mem": 12487680
      },
      "nGPU": 2
    },
    "mem": {
      "MemTotal": 32544216
    }
  },
```

Which looks pretty good to me

**Comment by amete** [comment]
No objections from my side, looks good. I was thinking we could have one entry per type (plus its count), to make the file a bit more compact but I don't think this is a real problem in practice. 

On a side note, it's interesting to see that the total memory for the same hardware type is different (albeit academical), which one could represent only w/ a unique entry per GPU. That's not on our side of course, but that's an interesting observation I was not expecting to be honest.

BTW, why do we store "TITAN" instead of "TITAN Xp"? Latter would be a bit more concise, no?

**Comment by graeme-a-stewart** [comment]
Yes, the memory difference is very odd, but it's there:

```
titanx:~/prmon$ nvidia-smi --query-gpu=count,memory.total,clocks.max.sm,gpu_n
ame --format=csv,noheader,nounits
2, 12196, 1911, TITAN Xp
2, 12195, 1911, TITAN Xp
```

`TITAN` instead of `TITAN Xp` is a bug on my side, let me fix that (I think the sstream parsing is stopping at the whitespace)

**Comment by graeme-a-stewart** [comment]
Fixed. So I think this is ready for a PR now, though I suggest we merge after feedback on a few points (e.g., the column name parsing).

**Comment by graeme-a-stewart** [comment]
> So I wonder, if in a machine w/ multiple GPUs (possibly different models) this prints each unique type w/ the total count or not. If so, this might make parsing the output a little easier perhaps. We can store one entry per type, instead of one per unit.

In fact `count` just prints the total number of GPUs, always the same, so it's not that useful.
