### ISSUE TITLE
Options to enable/disable monitoring components

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#107]
Currently `prmon` monitors basically everything it can. The #105 issue is adding support for NVIDIA GPU monitoring, which will only happen after a few tests.

This issue collects opinions on if we should allow prmon components to be enabled/disabled on the command line. At the moment there has been no request to do this and possibly no one really wants it...

**Comment by amete** [comment]
To be honest, I would implement this if there is a specific request from the users. For the time being the number of metrics we collect is fairly reasonable and there is not much overhead due to collecting all. If this changes in the future it might indeed be good to support toggling different components on/off but I don't see the need at this point of time from my experience.

**Comment by graeme-a-stewart** [comment]
So, implementing #113 actually made this quite strightforward to implement, so although there was no specific request for it, it seemed doable and useful. Implemeneted in #118.
