### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by graeme-a-stewart** [HSF/prmon#122]
As noticed in #112 we have an issue that newer Linux platforms usually only come with Python3 by default these days (Python2 is officially out of support from 2020-01-01).

As noted in <https://www.python.org/dev/peps/pep-0394/>, on unix systems `python3` and `python2` are preferred to refer to major Python versions. `python` is a wildcard - you could get either one (or nothing at all!).

I propose that we bite the bullet and make the next version of `prmon` Python3. Note that:

- Python is only needed for tests and for the plotter code, `prmon` itself is obviously compiled code and depends on CMake and the compiler.
- Python3 was even available on very old distributions (lxplus6 has Python3.4; Ubuntu16 has Python3.5).

So all scripts should update to `python3` shebang.

Note that the very old issue #44 can now also be solved properly.

One open question would be the minimum version to support. Format strings only arrived with Python3.6, but we may feel that dropping support for SLC6 and Ubuntu16 is still premature.

**Comment by graeme-a-stewart** [comment]
Python3 status in the various CI platforms:

| Distro | Python3 |
|-----|-----|
| Ubuntu16 | 3.5 |
| CentOS7 | 3.6 |
| Ubuntu18 | 3.6 |
| CentOS8 | 3.6 |
| Ubuntu20 | 3.8 |

There would be a strong case for saying 3.6 is the minimum supported version now, dropping Ubuntu16 from the CI set. What do you think @amete ?

**Comment by amete** [comment]
Hi @graeme-a-stewart,

In principle I strongly support this but at the same time wonder if it'll have any weird side effects. With my ATLAS hat on, I believe the main issue is the deployment (where we run the tests during building AtlasExternals) and the secondary issue is the plotting. We shouldn't break the first for sure, and the second can possibly be circumvented.

This bit is a bit ATLAS specific, but since we still haven't fully switched to Python 3, after setting up any master nightly w/ asetup, the system Python 3 becomes unusable because we overwrite PYTHONPATH. This, of course, is not a problem for `prmon` per se but at least the plotting script won't work unless it's executed w/ Python 2 as a script (which can be done). However, the real question is if we do anything special while building the externals that might clash w/ this.

Having said that, a pragmatic approach would be to do the switch and then test to see if it breaks anything downstream.

As for the CI, absolutely, let's drop anything that's older.

Best,
Serhan

**Comment by graeme-a-stewart** [comment]
Yes, I am aware, but I think that's also ATLAS's issue if they choose to destroy the Python3 setup on a machine then any modern Python scripts won't work.

In practice, it means building prmon in a Python3 LCG release *if you want to run the unit tests*. The counterexample is that on a moden platform should I be forced to install a whole out of date Python2 setup just to run prmon tests? I think that's unreasonable.

For the analysis script, one always has the option of forcing Python2, instead of relying on the shebang. It's pretty clear from https://github.com/HSF/prmon/pull/123/files#diff-f69ac4726b461fbd178b0b06ef3784fe that's going to still work right now (but actually, matplotlib, pandas and numpy have dropped Python2 support now, so this is one of the scripts one would most want to run in a modern Python3 setup).

Action though, *we should check exactly how prmon is being built and deployed in ATLAS at the moment.*

**Comment by graeme-a-stewart** [comment]
<https://gitlab.cern.ch/atlas/atlasexternals/-/blob/master/External/prmon/CMakeLists.txt>

**Comment by amete** [comment]
Yes, I integrated `prmon` into Athena a while back. As you noticed I added it into AtlasExternals:

https://gitlab.cern.ch/atlas/atlasexternals/-/tree/master/External/prmon

It's included in the list of external projects that are to be compiled for Athena:

https://gitlab.cern.ch/atlas/atlasexternals/-/blob/master/Projects/AthenaExternals/package_filters.txt

Then when we're building the nightly, the externals are built using:

https://gitlab.cern.ch/atlas/athena/-/blob/master/Projects/Athena/build_externals.sh

We have a Python3 nightly for master, Athena but that's not used for anything apart from testing at the moment. But I think both Python2 and Python3 builds are using the same externals tag:

https://gitlab.cern.ch/atlas/athena/-/blob/master/Projects/Athena/externals.txt

**Comment by amete** [comment]
Here is the actual script that builds the Externals, which I missed in the original message:

https://gitlab.cern.ch/atlas/athena/-/blob/master/Build/AtlasBuildScripts/build_atlasexternals.sh

**Comment by graeme-a-stewart** [comment]
OK, for the issue, see the fix in #123. With this implementation we keep the tests running in Python2 and in Python3 for the time being. Therefore no specific Python3 features can be used (stick to the Python2.7 feature set). For scripts that are just driving unit tests, like these, this is a feasible option.
